version: '3.8'

services:
  web1:
    image: ubuntu:22.04
    container_name: web1
    tty: true
    command: sleep infinity
    networks:
      lbnet:
        ipv4_address: 172.20.0.11

  web2:
    image: ubuntu:22.04
    container_name: web2
    tty: true
    command: sleep infinity
    networks:
      lbnet:
        ipv4_address: 172.20.0.12

  loadbalancer:
    image: ubuntu:22.04
    container_name: loadbalancer
    tty: true
    command: sleep infinity
    ports:
      - "8080:80"
    networks:
      lbnet:
        ipv4_address: 172.20.0.10

networks:
  lbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
