- name: Configure Nginx Load Balancer
  hosts: loadbalancer
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Set Nginx config template path
      set_fact:
        nginx_template: "templates/nginx_{{ lb_mode | default('round_robin') }}.conf.j2"

    - name: Deploy Nginx config
      template:
        src: "{{ nginx_template }}"
        dest: /etc/nginx/nginx.conf
        mode: '0644'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
